queryName: accountBenchmark
q1: |
  query accountByIds {
    accountByIds(id: [129583, 23980]) {
      accountId
      spn
      spnName
    }
  }
#
#table id, date, code,timestamp
#insert into table ('id', 'date', 'code'), (1, 2, 4)
#insert into table ('date', 'id', 'code'), (2, 1, 4)
#insert into xyz (csv.getHeaders()), (csv,getRow1())

r1: |
  {
    "data": {
      "accountByIds": [
        {
          "accountId": 23980,
          "spn": "2508346",
          "spnName": "JPMorgan Investment Funds - Global Select Equity Fund"
        },
        {
          "accountId": 129583,
          "spn": "2483343",
          "spnName": "Anandh Rural Bank DBA Anandh Rural Bank"
        }
      ]
    }
  }

q2: |
  query accountBenchmark {
    accountBenchmark(accountId: [23980, 129583,12345,23,98,66]) {
      edges {
        node {
          accountId
          benchmarkCode
          benchmarkUniverse
          benchmarkViewType
          endDate
          benchmarkTypeCode
        }
      }
    }
  }

r2: |
  {
    "data": {
      "accountBenchmark": {
        "edges": [
          {
            "node": {
              "accountId": 23980,
              "benchmarkCode": "WRLDRNRUSDO",
              "benchmarkUniverse": "CLOSING",
              "benchmarkViewType": "NDO",
              "endDate": null,
              "benchmarkTypeCode": "Attribution"
            }
          },
          {
            "node": {
              "accountId": 23980,
              "benchmarkCode": "WRLDRNRUSDO",
              "benchmarkUniverse": "CLOSING",
              "benchmarkViewType": "NDO",
              "endDate": null,
              "benchmarkTypeCode": "Official"
            }
          },
          {
            "node": {
              "accountId": 23980,
              "benchmarkCode": "BMK11247",
              "benchmarkUniverse": "CLOSING",
              "benchmarkViewType": "COB",
              "endDate": "2018-11-30",
              "benchmarkTypeCode": "Official"
            }
          },
          {
            "node": {
              "accountId": 129583,
              "benchmarkCode": "LOND6033WOOD",
              "benchmarkUniverse": "CLOSING",
              "benchmarkViewType": "COB",
              "endDate": "2014-09-30",
              "benchmarkTypeCode": "Official"
            }
          }
        ]
      }
    }
  }

q3: |
  query accountByIds {
    accountByIds(id: [23980, 129583,12345,23,98,66]) {
      accountId
      primarySystem {
        code
        test {
          test1
          test2
        }
      }
      code
      longName
      shortName
      briefName
      accountStatusType {
        code
        name
      }
      accountType {
        code
      }
      startDate
      endDate
      fundingEvent {
        intendedFundingDate
        date
      }
      managementResponsibilityCenter {
        code
        name
      }
      investmentSubVehicle {
        code
        investmentVehicle {
          code
        }
      }
    }
  }

r3: |
  {
    "data": {
      "accountByIds": [
        {
          "accountId": 23980,
          "primarySystem": {
            "code": "WSSL"
          },
          "code": "11247",
          "longName": "11247 - 2 - long nm",
          "shortName": "11247 -2- short nm",
          "briefName": "11247 -2",
          "accountStatusType": {
            "code": "A",
            "name": "Active"
          },
          "accountType": {
            "code": "N"
          },
          "startDate": "1997-11-19",
          "endDate": null,
          "fundingEvent": {
            "intendedFundingDate": null,
            "date": null
          },
          "managementResponsibilityCenter": {
            "code": "EQL",
            "name": "Equity JPM London"
          },
          "investmentSubVehicle": {
            "code": "SEPM",
            "investmentVehicle": {
              "code": "SEPM"
            }
          },
        },
        {
          "accountId": 129583,
          "primarySystem": {
            "code": "WSSL"
          },
          "code": "713601",
          "longName": "713601 - 2 - long nm",
          "shortName": "713601 -2- short nm",
          "briefName": "713601 -2",
          "accountStatusType": {
            "code": "CLOC",
            "name": "Closed - Outside custody"
          },
          "accountType": {
            "code": "A"
          },
          "startDate": "1998-10-26",
          "endDate": "2013-12-27",
          "fundingEvent": {
            "intendedFundingDate": null,
            "date": null
          },
          "managementResponsibilityCenter": {
            "code": "LOND",
            "name": "JPM London"
          },
          "investmentSubVehicle": {
            "code": "SEPM",
            "investmentVehicle": {
              "code": "SEPM"
            }
          },
        }
      ]
    }
  }

q4: |
  query accountBenchmark {
    accountBenchmark(accountId: [23980, 129583,12345,23,98,66]) {
      edges {
        node {
          accountId
          benchmarkCode
          benchmarkUniverse
          benchmarkViewType
          endDate
          benchmarkTypeCode
            {
              code
              name
            }
        }
      }
    }
  }

r4: |
  {
    "data": {
      "accountBenchmark": {
        "edges": [
          {
            "node": { 
              "accountId": 23980,
              "benchmarkCode": "WRLDRNRUSDO",
              "benchmarkUniverse": "CLOSING",
              "benchmarkViewType": "NDO",
              "endDate": null,
              "benchmarkTypeCode": [
                  {
                "code": 123,
                 "name" : "Test1"
                  },
                {
                "code": 456,
                 "name" : "Test2"
                  },
                 {
                "code": 789,
                 "name" : "Test3"
                  },
                 {
                "code": 258,
                 "name" : "Test4"
                  }
                ]
            }
          },
          {
            "node": {
              "accountId": 23980,
              "benchmarkCode": "WRLDRNRUSDO",
              "benchmarkUniverse": "CLOSING",
              "benchmarkViewType": "NOO",
              "endDate": "2014-10-30",
              "benchmarkTypeCode": null,
            }
          },
          {
            "node": {
              "accountId": 23980,
              "benchmarkCode": "BMK11247",
              "benchmarkUniverse": "CLOSING",
              "benchmarkViewType": "COB",
              "endDate": "2018-11-30",
              "benchmarkTypeCode": null,
            }
          },
          {
            "node": {
              "accountId": 129583,
              "benchmarkCode": "LOND6033WOOD",
              "benchmarkUniverse": "CLOSING",
              "benchmarkViewType": "COB",
              "endDate": "2014-09-30",
              "benchmarkTypeCode": null,
            }
          }
        ]
      }
    }
  }

q5: |
  query accountHierarchy {
    accountHierarchy (accountId: [181834, 181835])  {
      edges {
        node {
          childAccount {
            accountId
            code
            shortName
            primarySystem {
              code
            }
            accountStatusType {
              code
            }
            accountHierarchyType {
              code
              name
            }
          }
          parentAccount {
            accountId
            code
            shortName
            primarySystem {
              code
            }
            accountStatusType {
              code
              name
            }
            accountHierarchyType {
              code
              name
            }
          }
        }
      }
    }
  }

r5: |
  {
    "data": {
      "accountHierarchy": {
        "edges": [
          {
            "node": {
              "childAccount": {
                "accountId": 181834,
                "code": "71407",
                "shortName": "71407 -2- short nm",
                "primarySystem": {
                  "code": "WSSL"
                },
                "accountStatusType": {
                  "code": "A"
                },
                "accountHierarchyType": {
                  "code": "standalone",
                  "name": "Stand-alone"
                }
              },
              "parentAccount": {
                "accountId": 181837,
                "code": "593064",
                "shortName": "593064 -2- short nm",
                "primarySystem": {
                  "code": "BNYL"
                },
                "accountStatusType": {
                  "code": "CLOC",
                  "name": "Closed - Outside custody"
                },
                "accountHierarchyType": null
              }
            }
          },
          {
            "node": {
              "childAccount": {
                "accountId": 181834,
                "code": "71407",
                "shortName": "71407 -2- short nm",
                "primarySystem": {
                  "code": "WSSL"
                },
                "accountStatusType": {
                  "code": "A"
                },
                "accountHierarchyType": {
                  "code": "standalone",
                  "name": "Stand-alone"
                }
              },
              "parentAccount": {
                "accountId": 181837,
                "code": "593064",
                "shortName": "593064 -2- short nm",
                "primarySystem": {
                  "code": "BNYL"
                },
                "accountStatusType": {
                  "code": "CLOC",
                  "name": "Closed - Outside custody"
                },
                "accountHierarchyType": null
              }
            }
          },
          {
            "node": {
              "childAccount": {
                "accountId": 181835,
                "code": "536685",
                "shortName": "536685 -2- short nm",
                "primarySystem": {
                  "code": "BNYL"
                },
                "accountStatusType": {
                  "code": "CLOC"
                },
                "accountHierarchyType": null
              },
              "parentAccount": {
                "accountId": 181837,
                "code": "593064",
                "shortName": "593064 -2- short nm",
                "primarySystem": {
                  "code": "BNYL"
                },
                "accountStatusType": {
                  "code": "CLOC",
                  "name": "Closed - Outside custody"
                },
                "accountHierarchyType": null
              }
            }
          },
          {
            "node": {
              "childAccount": {
                "accountId": 181835,
                "code": "536685",
                "shortName": "536685 -2- short nm",
                "primarySystem": {
                  "code": "BNYL"
                },
                "accountStatusType": {
                  "code": "CLOC"
                },
                "accountHierarchyType": null
              },
              "parentAccount": {
                "accountId": 181837,
                "code": "593064",
                "shortName": "593064 -2- short nm",
                "primarySystem": {
                  "code": "BNYL"
                },
                "accountStatusType": {
                  "code": "CLOC",
                  "name": "Closed - Outside custody"
                },
                "accountHierarchyType": null
              }
            }
          }
        ]
      }
    }
  }

q6: |
  query account {
    account(id: 2090192) {
      edges {
        node {
          accountId
          code
          primarySystem {
            code
          }
          accountProduct {
            strategy
            desk
          }
          ownedByAccount {
            account {
              accountId
              code
              accountProduct {
                strategy
                desk
              }
            }
          }
        }
      }
    }
  }

r6: |
  {
    "data": {
      "account": {
        "edges": [
          {
            "node": {
              "accountId": 2090192,
              "code": "166380",
              "primarySystem": {
                "code": "RAFA"
              },
              "accountProduct": {
              "strategy": "A184E31436854C73BF2D1936715C8BD4",
              "desk": "301508"
                },
              "ownedByAccount": {
                "account": {
                  "accountId": 2090192,
                  "code": "166380",
                  "accountProduct": {
                    "strategy": "A184E31436854C73BF2D1936715C8BD4",
                    "desk": "301508"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
